# -*- coding: utf-8 -*-
"""Portuguese (Brazil) deck — "01x01 A Loira do Banheiro".

Targets the A1 jump for a Spanish speaker: only what is NOT transparent from
Spanish. Transparent cognates (beleza, concurso, premio, pocao, gato, lenda...)
are deliberately left out; false friends and spoken formulas are the payload.
Back content is in ENGLISH (the bridge language) so Spanish never plants the
false friends it would otherwise reinforce.

Sentences are taken from the YouTube video transcript (heavy ASR typos fixed;
unrecoverable stretches were not harvested).

Run:  python tools/deck_portuguese_loira.py   ->  portuguese/loira-do-banheiro.apkg
"""

import deck_builder

LANGUAGE = "portuguese"
SLUG = "loira-do-banheiro"
DECK_ID = 1987452330   # stable: re-import updates instead of duplicating
LEVEL = "a1"

SOURCE_URL = "https://www.youtube.com/watch?v=9XYk01N8Xbk"
DESCRIPTION = (
    "Portuguese (Brazil) &middot; A1. Everyday vocabulary, spoken formulas and "
    "basic grammar from <i>Historietas Assombradas 01x01 &mdash; A Loira do "
    "Banheiro</i>. Curated for a Spanish speaker: words transparent from Spanish "
    "are skipped, false friends are prioritised. English carries the gloss."
    + (f"<br>Source video: <a href='{SOURCE_URL}'>{SOURCE_URL}</a>" if SOURCE_URL else "")
)

CARDS = [
    # ============ EVERYDAY VOCABULARY ============
    dict(plane="vocab", term="banheiro",
         text="A mulher que mora no espelho do {{c1::banheiro}} das meninas.",
         meaning="bathroom / restroom",
         intention="One of the first place words you need: the room with toilet and shower.",
         image="Tiles, a sink, a mirror, a closed door.",
         note="FALSE FRIEND: not Spanish 'bañero' (lifeguard). Masculine: o banheiro."),
    dict(plane="vocab", term="espelho",
         text="A mulher que mora no {{c1::espelho}} do banheiro das meninas.",
         meaning="mirror",
         intention="Everyday object; here it is where the ghost lives.",
         image="A bathroom mirror you say a name into three times.",
         note="Spelling trap: -lh- = the Spanish 'j' sound is NOT here. espelho = espejo."),
    dict(plane="vocab", term="mulher",
         text="A {{c1::mulher}} que mora no espelho do banheiro das meninas.",
         meaning="woman",
         intention="Core person word; also 'wife' in context.",
         image="A grown woman, as opposed to a menina.",
         note="Same -lh- trap as espelho. mulher = mujer."),
    dict(plane="vocab", term="menina",
         text="Era a {{c1::menina}} mais bonita na escola.",
         meaning="girl",
         intention="The everyday word for a young girl; pairs with menino.",
         image="A schoolgirl in the hallway.",
         note="Not transparent from Spanish 'niña'. Feminine: a menina."),
    dict(plane="vocab", term="barata",
         text="Obrigada, Ritinha. Mas isso é uma {{c1::barata}}.",
         meaning="cockroach",
         intention="You will meet this word in any Brazilian kitchen joke.",
         image="A brown cockroach handed over as a lucky charm.",
         note="FALSE FRIEND: not Spanish 'barata' (cheap). Feminine: uma barata."),
    dict(plane="vocab", term="frango",
         text="O {{c1::frango}} frito mais gorduroso do Condado.",
         meaning="chicken (the meat)",
         intention="Core food word — on every menu in Brazil.",
         image="A basket of fried chicken.",
         note="Nothing like Spanish 'pollo'. Masculine: o frango."),
    dict(plane="vocab", term="gorduroso",
         text="O frango frito mais {{c1::gorduroso}} do Condado.",
         meaning="greasy / fatty",
         intention="Describe food that drips; also skin and hair.",
         image="Oil soaking through the paper bag.",
         note="From gordura (fat). Feminine: gordurosa."),
    dict(plane="vocab", term="lanchonete",
         text="A melhor {{c1::lanchonete}} temática da cidade.",
         meaning="snack bar / diner",
         intention="Where you get a quick bite — the default casual eating place.",
         image="A counter with burgers and a soda barrel.",
         note="From lanche (snack). No Spanish equivalent word. Feminine: a lanchonete."),
    dict(plane="vocab", term="cardápio",
         text="Pagam tudo que tem no {{c1::cardápio}} em dobro.",
         meaning="menu",
         intention="What you ask for the moment you sit down at a restaurant.",
         image="A laminated menu handed to you at the table.",
         note="Nothing like Spanish 'carta' or 'menú'. Masculine: o cardápio."),
    dict(plane="vocab", term="trevas",
         text="E amanhã é o concurso de beleza das {{c1::trevas}}.",
         meaning="darkness (literary / dramatic)",
         intention="The dramatic word for darkness — used for anything spooky.",
         image="A pitch-black hall lit by one torch.",
         note="Always plural: as trevas. Spanish would be 'tinieblas'."),
    dict(plane="vocab", term="avó",
         text="Marilu, bebe essa poção que a minha {{c1::avó}} fez.",
         meaning="grandmother",
         intention="Core family word.",
         image="A grandmother brewing something in a pot.",
         note="Careful: avó (grandmother) vs avô (grandfather) — the accent changes the vowel."),
    dict(plane="vocab", term="saco",
         text="Vamos só colocar esse {{c1::saco}} na sua cabeça por enquanto.",
         meaning="bag / sack",
         intention="A plain bag — paper, plastic or cloth.",
         image="A paper bag pulled over someone's head.",
         note="Masculine: o saco. In slang 'que saco!' = what a drag!"),
    dict(plane="vocab", term="chave",
         text="Esqueci a {{c1::chave}}, abre para mim.",
         meaning="key",
         intention="Core object word — doors, locks, cars.",
         image="A key you left on the other side of the door.",
         note="Not transparent from Spanish 'llave'. Feminine: a chave."),
    dict(plane="vocab", term="rótulo",
         text="Não leu o {{c1::rótulo}}, Vanda: use com parcimônia.",
         meaning="label (on a bottle or jar)",
         intention="What you are supposed to read before drinking the potion.",
         image="The small printed label on a bottle.",
         note="Narrower than Spanish 'rótulo' (sign). Masculine: o rótulo."),
    dict(plane="vocab", term="contrato",
         text="Você leu as letrinhas do {{c1::contrato}}?",
         meaning="contract",
         intention="Any written agreement — here, the one with the ghost.",
         image="A long scroll with tiny print at the bottom.",
         note="Masculine: o contrato."),
    dict(plane="vocab", term="letrinhas",
         text="Você leu as {{c1::letrinhas}} do contrato?",
         meaning="the fine print (literally 'little letters')",
         intention="The part of an agreement nobody reads and everybody regrets.",
         image="A magnifying glass over microscopic text.",
         note="letra + -inha. The diminutive is what makes it mean 'fine print'."),
    dict(plane="vocab", term="maquiagem",
         text="Vamos tirar essa {{c1::maquiagem}}, tá bom?",
         meaning="makeup",
         intention="Core everyday noun; the whole episode turns on it.",
         image="Lipstick, powder and a brush.",
         note="From the French. Feminine: a maquiagem."),
    dict(plane="vocab", term="boneca",
         text="Não, Marilu, você não é uma {{c1::boneca}}.",
         meaning="doll",
         intention="A toy doll; also said of a person who looks unnaturally perfect.",
         image="A porcelain doll with painted cheeks.",
         note="Nothing like Spanish 'muñeca'. Diminutive bonequinha is all over this episode."),
    dict(plane="vocab", term="dança",
         text="{{c1::Dança}} da vitória!",
         meaning="dance",
         intention="Core noun; the verb is dançar.",
         image="A little victory jig.",
         note="The ç keeps the 's' sound. Feminine: a dança."),

    # ============ SPOKEN FORMULAS ============
    dict(plane="expression", term="tudo bom?",
         text="{{c1::Tudo bom}}? Tem alguma coisa divertida para fazer hoje?",
         meaning="how's it going? / all good?",
         intention="The default Brazilian greeting — you will hear it before anything else.",
         note="Answer with 'tudo bom' or 'tudo bem'. Both work as question and answer."),
    dict(plane="expression", term="tudo bem",
         text="{{c1::Tudo bem}}, come só uma saladinha.",
         meaning="it's fine / okay / no problem",
         intention="Wave away an objection; also a greeting like tudo bom.",
         note="Here it is reassurance, not a greeting. Tone decides."),
    dict(plane="expression", term="tá bom",
         text="{{c1::Tá bom}}, a vencedora é Marilu.",
         meaning="okay / alright / fine",
         intention="Give in, or move things along. Spoken constantly.",
         note="Short for 'está bom'. Even shorter: just 'tá'."),
    dict(plane="expression", term="beleza",
         text="{{c1::Beleza}}. Qual é o nome dela?",
         meaning="okay / cool / deal",
         intention="Agree to something, casually — the most Brazilian 'okay' there is.",
         note="Literally 'beauty', but used as agreement. Note the irony: this episode "
              "is about beleza in the literal sense."),
    dict(plane="expression", term="né?",
         text="A Marilu, {{c1::né}}?",
         meaning="right? / isn't it?",
         intention="Tag a question onto anything to check the other person agrees.",
         note="Squashed from 'não é'. Ends half the sentences in spoken Brazilian."),
    dict(plane="expression", term="cadê?",
         text="E {{c1::cadê}} ela?",
         meaning="where is...?",
         intention="Ask where something or someone is — nothing else needed, no verb.",
         note="No Spanish equivalent at all; you have to learn it whole. "
              "From 'que é de'. Followed directly by the noun: cadê o Pepe?"),
    dict(plane="expression", term="sério?",
         text="{{c1::Sério}}, Ritinha? Você me acha bonita mesmo?",
         meaning="really? / seriously?",
         intention="React to something surprising or hard to believe.",
         note="Also 'sério mesmo?' for extra disbelief."),
    dict(plane="expression", term="cruz credo",
         text="Ele me deu uma poção para eu ficar bonita. — {{c1::Cruz credo}}!",
         meaning="good heavens! / yikes!",
         intention="React with horror or disgust at something you find awful.",
         note="Old and slightly comic, from a prayer. Very common with grandmothers."),
    dict(plane="expression", term="fica à vontade",
         text="Claro, meu bem, pode entrar, {{c1::fica à vontade}}.",
         meaning="make yourself at home / help yourself",
         intention="Tell a visitor to relax and act freely in your space.",
         note="Literally 'stay at will'. Here it is a trap, said by the ghost."),
    dict(plane="expression", term="tarde demais",
         text="{{c1::Tarde demais}}, querida.",
         meaning="too late",
         intention="Shut down a request that came after the deadline.",
         note="demais after an adjective = 'too much'. Also caro demais, longe demais."),
    dict(plane="expression", term="valeu",
         text="{{c1::Valeu}} por ter me salvado.",
         meaning="thanks! / cheers!",
         intention="Casual thank-you between friends — never in a formal setting.",
         note="From valer (to be worth). Use obrigado/obrigada when in doubt."),
    dict(plane="expression", term="droga",
         text="Você! Que que eu faço? {{c1::Droga}}!",
         meaning="damn! / crap!",
         intention="Mild swearing at your own bad luck. Safe to use.",
         note="FALSE FRIEND as an interjection: the noun does mean 'drug', "
              "but thrown out alone it is just 'damn'."),

    # ============ GRAMMAR ============
    dict(plane="grammar", term="tô",
         text="Não {{c1::tô}} com fome.",
         meaning="I am (spoken form of 'estou')",
         intention="How Brazilians actually say 'estou' — you need it to hear anything.",
         pattern="estou -> tô · estamos -> tamo",
         note="Never written in formal Portuguese, always said in speech."),
    dict(plane="grammar", term="tá",
         text="Não liga, Marilu. Você {{c1::tá}} linda.",
         meaning="you are / it is (spoken form of 'está')",
         intention="The partner of tô, for você / ele / ela.",
         pattern="está -> tá · estava -> tava",
         note="'tá bom' and 'tá' alone also mean 'okay'."),
    dict(plane="grammar", term="a gente",
         text="{{c1::A gente}} podia ter ido comer lá.",
         meaning="we (spoken)",
         intention="How Brazilians say 'we' most of the time, instead of nós.",
         pattern="a gente + verb in the HE/SHE form (a gente vai, a gente foi)",
         note="Grammatically singular even though it means 'we'. "
              "Careful: plain 'gente' (no 'a') means 'you guys' — see deck globo-da-morte."),
    dict(plane="grammar", term="pra",
         text="Deve ter ido atrás da Vanda {{c1::pra}} retocar a maquiagem.",
         meaning="to / for (spoken form of 'para')",
         intention="Squashed 'para' — what you will actually hear.",
         pattern="para -> pra · para o -> pro · para a -> pra",
         note="Written informally too, in messages and subtitles."),
    dict(plane="grammar", term="saladinha",
         text="Tudo bem, come só uma {{c1::saladinha}}.",
         meaning="a little salad",
         intention="The diminutive: makes things small, but mostly makes them friendly.",
         pattern="noun + -inho (M) / -inha (F)",
         note="Productive engine of Brazilian Portuguese, far more than in Spanish. "
              "This episode alone: bonitinha, pouquinho, criaturinha, queridinha, "
              "letrinhas, Ritinha, bonequinha."),
    dict(plane="grammar", term="tô torcendo",
         text="Espero que você ganhe, {{c1::tô torcendo}} por você.",
         meaning="I'm rooting (for you)",
         intention="The continuous: something happening right now.",
         pattern="estar + verb-NDO (tô comendo, tá chovendo, tava dormindo)",
         note="Brazil uses estar + -ndo. Portugal says 'estar a + infinitive' instead."),
    dict(plane="grammar", term="sabe ler não?",
         text="{{c1::Sabe ler não}}? Aqui diz: use com parcimônia.",
         meaning="can't you read?",
         intention="Negation thrown to the END of the sentence — very Brazilian, informal.",
         pattern="verb + não  (quero não · sei não · tem não)",
         note="The standard form would be 'não sabe ler?'. The final-não version "
              "sounds casual, sometimes impatient."),

    # ============ VERBS & CONSTRUCTIONS ============
    dict(plane="verb-construction", term="ficar",
         text="Não se preocupa. Você vai {{c1::ficar}} linda.",
         meaning="to become / to get / to end up",
         intention="Change of state: ficar bonita, ficar bravo, ficar triste.",
         pattern="ficar + adjective = become that",
         synonyms="tornar-se (formal), virar (casual)",
         note="No single Spanish verb covers it — quedar, ponerse and volverse all "
              "land here. Also means 'to stay': fica aqui."),
    dict(plane="verb-construction", term="com fome",
         text="Não tô {{c1::com fome}}.",
         meaning="hungry",
         intention="Say you are hungry, thirsty, sleepy, cold, afraid.",
         pattern="estar com + noun (com fome, com sede, com sono, com frio, com medo)",
         note="STRUCTURAL TRAP: Spanish uses TENER hambre; Portuguese uses ESTAR COM. "
              "Saying 'tenho fome' marks you as a Spanish speaker immediately."),
    dict(plane="verb-construction", term="temos que",
         text="Eu aprendi que {{c1::temos que}} ler contratos.",
         meaning="we have to / we must",
         intention="Obligation — the everyday way to say it.",
         pattern="ter que + infinitive (tenho que ir, tem que ler)",
         synonyms="ter de (more formal), precisar de"),
    dict(plane="verb-construction", term="dá para",
         text="Bom, vamos ver o que {{c1::dá para}} fazer.",
         meaning="it's possible to / one can",
         intention="Ask or say whether something can be done at all.",
         pattern="dá para + infinitive (dá para ver? dá para ir a pé)",
         note="Impersonal — no subject. Very high frequency in speech."),
    dict(plane="verb-construction", term="liga",
         text="Não {{c1::liga}}, Marilu. Você tá linda.",
         meaning="don't mind it / pay no attention",
         intention="Tell someone to let an insult or a problem go.",
         pattern="ligar para / ligar de = to care about",
         note="FALSE FRIEND: not Spanish 'ligar' (to flirt). ligar also means "
              "'to phone' and 'to switch on' — three separate lives."),
    dict(plane="verb-construction", term="Esqueci",
         text="{{c1::Esqueci}} a chave, abre para mim.",
         meaning="I forgot",
         intention="Core everyday verb; you will need the first person constantly.",
         pattern="esquecer (esqueci, esqueceu, esquecemos)",
         note="Nothing like Spanish 'olvidar'. Also esquecer-se DE algo."),
    dict(plane="verb-construction", term="torcendo por",
         text="Espero que você ganhe, tô {{c1::torcendo por}} você.",
         meaning="rooting for / supporting",
         intention="Say you want someone to win — football, exams, anything.",
         pattern="torcer por + person/team",
         note="FALSE FRIEND: Spanish 'torcer' means to twist. In Brazil a torcida "
              "is the crowd of supporters."),
]

if __name__ == "__main__":
    deck_builder.build(LANGUAGE, SLUG, DECK_ID, CARDS, LEVEL, DESCRIPTION)
