# -*- coding: utf-8 -*-
"""French deck — "Le gentil petit Diable" (Contes de la rue Broca).

Targets the A1 band: school and family vocabulary, spoken reactions, and the
small grammar this tale keeps repeating. Third French deck, so nothing repeats
from sorciere-rue-mouftard or from french/motor (checked with tools/cobertura.py)
- that rules out il y a, il me faut, je voudrais, tant pis, bien sur, d'accord,
the articles, ne...pas and the question words.

Sentences are taken from the YouTube video transcript (obvious ASR typos fixed).

Run:  python tools/deck_french_diable.py   ->  french/gentil-petit-diable.apkg
"""

import deck_builder

LANGUAGE = "french"
SLUG = "gentil-petit-diable"
DECK_ID = 1987452322   # stable: re-import updates instead of duplicating
LEVEL = "a1"

SOURCE_URL = "https://www.youtube.com/watch?v=ktPWVk71Vx8"
DESCRIPTION = (
    "French &middot; A1. School and family vocabulary, spoken reactions and small "
    "grammar from <i>Le gentil petit Diable</i> (Contes de la rue Broca). Curated "
    "against the other French decks, so nothing repeats from "
    "<i>sorciere-rue-mouftard</i> or <i>motor</i>. English carries the gloss."
    + (f"<br>Source video: <a href='{SOURCE_URL}'>{SOURCE_URL}</a>" if SOURCE_URL else "")
)

CARDS = [
    # ============ EVERYDAY VOCABULARY ============
    dict(plane="vocab", term="enfer",
         text="L'histoire commence en {{c1::enfer}}.",
         meaning="hell",
         intention="Where this whole tale is set; also figurative ('c'est l'enfer').",
         image="A boiler room with fires that must be kept burning.",
         note="Masculine: l'enfer. Opposite: le paradis."),
    dict(plane="vocab", term="diable",
         text="Et c'est comme ça que le gentil petit {{c1::diable}} finit par se retrouver ange au paradis.",
         meaning="devil",
         intention="The title character; also an exclamation in older French.",
         image="A small red devil with horns and a tail.",
         note="Masculine: le diable."),
    dict(plane="vocab", term="ange",
         text="Fais bien attention, l'{{c1::ange}} de la lecture est très sévère.",
         meaning="angel",
         intention="The devil's counterpart; also 'tu es un ange' = you're a darling.",
         image="An examiner with wings and a halo.",
         note="Masculine even for a female angel: un ange."),
    dict(plane="vocab", term="feu",
         text="Ne pas laisser ton {{c1::feu}} s'étouffer.",
         meaning="fire",
         intention="Core word: fire, a light, a traffic light, a cigarette light.",
         image="A furnace you must keep burning under the customers.",
         note="Masculine: le feu. Plural: les feux."),
    dict(plane="vocab", term="devoirs",
         text="Naturellement, tu avais fait tous tes {{c1::devoirs}}.",
         meaning="homework",
         intention="What school sends you home with — always plural in this sense.",
         image="An exercise book finished at the kitchen table.",
         note="Masculine plural: les devoirs. In the singular, le devoir = duty."),
    dict(plane="vocab", term="leçons",
         text="Et tu savais tes {{c1::leçons}}?",
         meaning="lessons (the material you learn by heart)",
         intention="'Savoir ses lecons' = to have learnt them — a fixed school phrase.",
         image="Reciting what you memorised last night.",
         note="Feminine: une lecon. Also 'donner une lecon' = to teach someone a lesson."),
    dict(plane="vocab", term="dictée",
         text="J'ai fait une {{c1::dictée}}, des problèmes, un peu d'histoire et de la géographie.",
         meaning="dictation (the classic French school exercise)",
         intention="A cultural institution — every French child has suffered one.",
         image="The teacher reading aloud while you write every accent.",
         note="Feminine: une dictée. From dicter."),
    dict(plane="vocab", term="école",
         text="Dès demain je te retire de l'{{c1::école}} et je te mets au travail.",
         meaning="school",
         intention="Core place word.",
         image="The school gate you are being pulled away from.",
         note="Feminine: une école, l'école. Aller à l'école = to go to school."),
    dict(plane="vocab", term="cornes",
         text="Un ange avec une queue et des {{c1::cornes}}, on n'a jamais vu ça.",
         meaning="horns",
         intention="On an animal, a devil, or a helmet.",
         image="Two little red horns on a child's head.",
         note="Feminine: une corne. Also a car horn = un klaxon, not une corne."),
    dict(plane="vocab", term="queue",
         text="Un ange avec une {{c1::queue}} et des cornes, on n'a jamais vu ça.",
         meaning="tail; also a queue / line of people",
         intention="Two meanings you will need: an animal's tail, and the line at a shop.",
         image="A pointed devil's tail.",
         note="Feminine: une queue. 'Faire la queue' = to queue up. "
              "Pronounced like 'keu' — the -ueue is one sound."),
    dict(plane="vocab", term="ailes",
         text="Tu as des {{c1::ailes}}, c'est le moment de t'en servir.",
         meaning="wings",
         intention="On birds, planes, angels and devils.",
         image="Small bat wings on the devil's back.",
         note="Feminine: une aile. Silent -s in the plural, as always."),
    dict(plane="vocab", term="gamin",
         text="Tu m'as compris, {{c1::gamin}}?",
         meaning="kid / youngster",
         intention="Address or refer to a child — familiar, a bit rough.",
         image="The boss barking at the boy.",
         note="Feminine: gamine. Familiar register: fine with family, not with strangers."),
    dict(plane="vocab", term="môme",
         text="Tu me plais, tu es un brave {{c1::môme}}.",
         meaning="kid (slang)",
         intention="Same idea as gamin, even more colloquial and affectionate here.",
         image="The convict patting the little devil on the head.",
         note="Both genders: un môme / une môme. Very spoken; never written formally."),
    dict(plane="vocab", term="patron",
         text="Soyez tranquille, {{c1::patron}}.",
         meaning="boss",
         intention="Your employer; also the owner of a café or shop.",
         image="The devil in charge of the boiler room.",
         note="Feminine: la patronne. Used as a direct address, like 'boss'."),
    dict(plane="vocab", term="gentil",
         text="Je veux être {{c1::gentil}}.",
         meaning="kind / nice / good (of a child)",
         intention="The word this whole tale turns on: being good rather than naughty.",
         image="A devil who wants to be nice.",
         note="Feminine: gentille (double L, and you hear it). "
              "'C'est gentil' = that's kind of you."),
    dict(plane="vocab", term="méchant",
         text="Justement, mes parents ils veulent que je sois {{c1::méchant}}.",
         meaning="mean / nasty / naughty",
         intention="The opposite of gentil; used for children, dogs and villains.",
         image="The devil parents demanding bad behaviour.",
         note="Feminine: méchante. 'Chien méchant' = beware of the dog."),
    dict(plane="vocab", term="vacances",
         text="Peut-être qu'on pourra aller le voir pour les {{c1::vacances}}.",
         meaning="holidays / vacation",
         intention="Core everyday noun — always plural in French.",
         image="The devil family packing for Paradise.",
         note="Feminine plural, never singular: les vacances, en vacances."),

    # ============ SPOKEN REACTIONS ============
    dict(plane="expression", term="faut pas le répéter",
         text="Dans le placard il y a une sorcière, {{c1::faut pas le répéter}}.",
         meaning="you mustn't tell / don't repeat it",
         intention="Share a secret — the refrain of the series' theme song.",
         note="Spoken French drops the 'il' of 'il faut': 'faut pas' = you mustn't. "
              "You will hear this dropping everywhere: 'faut y aller'."),
    dict(plane="expression", term="mince alors",
         text="{{c1::Mince alors}}! Des hommes!",
         meaning="blimey! / wow! / oh no!",
         intention="React to a surprise. Completely safe — it is the polite swear word.",
         note="'Mince' literally means thin. Used instead of a rude word."),
    dict(plane="expression", term="ma foi",
         text="{{c1::Ma foi}}, tant pis, je vais écrire n'importe quoi.",
         meaning="well / honestly / I must say",
         intention="Resign yourself out loud before making a decision.",
         note="Literally 'my faith'. Slightly old-fashioned, very common in tales."),
    dict(plane="expression", term="quelle affaire",
         text="Tes parents? {{c1::Quelle affaire}}!",
         meaning="what a business! / what a mess!",
         intention="React to a complicated problem someone just handed you.",
         pattern="quel / quelle + noun = what a...! (quelle horreur, quelle chance)"),
    dict(plane="expression", term="ben non",
         text="Au moins tu t'es bien battu avec tes camarades? — {{c1::Ben non}}, papa.",
         meaning="well, no / nope",
         intention="Answer no, hesitantly or apologetically.",
         note="'Ben' is spoken 'eh bien', squashed. Also 'ben oui', 'ben voilà'."),
    dict(plane="expression", term="tu l'as dit",
         text="Il fait chaud. — {{c1::Tu l'as dit}}, mon enfant.",
         meaning="you said it / you can say that again",
         intention="Agree emphatically with what someone just said.",
         note="Literally 'you said it'. Same use as in English."),
    dict(plane="expression", term="rien à faire",
         text="Ça ne marche pas. — {{c1::Rien à faire}}, mon gars.",
         meaning="no way / nothing doing / it's hopeless",
         intention="Declare that an attempt has failed for good.",
         note="Literally 'nothing to do'."),
    dict(plane="expression", term="trop tard",
         text="Excusez-moi monsieur. — {{c1::Trop tard}}, je ferme.",
         meaning="too late",
         intention="Refuse a request that arrived after the moment had passed.",
         note="'Il est trop tard' in full; alone it is blunter."),
    dict(plane="expression", term="doucement",
         text="Eh, {{c1::doucement}}! On n'est pas aux pièces.",
         meaning="easy! / slow down! / gently",
         intention="Tell someone to slow down or calm down.",
         note="From doux (soft). Also means 'quietly' and 'slowly'."),
    dict(plane="expression", term="tiens",
         text="{{c1::Tiens}}, pour lui faire plaisir.",
         meaning="here (you go) / look / well well",
         intention="Hand something over, or flag a small surprise.",
         note="Imperative of tenir. Plural/polite: tenez. "
              "'Tiens, tiens' alone = well well, interesting."),
    dict(plane="expression", term="n'importe quoi",
         text="Ma foi tant pis, je vais écrire {{c1::n'importe quoi}}.",
         meaning="anything at all / any old thing; also 'rubbish, nonsense'",
         intention="Say you will do something without choosing — or dismiss what someone said.",
         pattern="n'importe + quoi / qui / où / quand / comment",
         note="'C'est n'importe quoi!' = that's nonsense! Extremely common."),
    dict(plane="expression", term="pas mal",
         text="{{c1::Pas mal}}. Vous savez, papa Saïd, Bachir n'est peut-être pas fait pour les études.",
         meaning="not bad",
         intention="Faint praise, or genuine approval depending on tone.",
         note="Also means 'quite a lot': 'pas mal de gens' = quite a few people."),

    # ============ GRAMMAR ============
    dict(plane="grammar", term="Regardez-moi",
         text="Monsieur Pierre, {{c1::regardez-moi}} le plus beau!",
         meaning="look at him, would you",
         intention="In a POSITIVE command the pronoun jumps to the END, with a hyphen.",
         pattern="VERB-moi / -toi / -le / -nous  (donne-moi, regardez-moi, dis-le)",
         note="This is the exception to the rule that pronouns go before the verb. "
              "Make it negative and it flips back: 'ne me regardez pas'. "
              "And 'me' becomes 'moi' when it lands at the end."),
    dict(plane="grammar", term="le plus haut",
         text="Envole-toi et monte {{c1::le plus haut}} que tu peux.",
         meaning="the highest / as high as",
         intention="The superlative: say something is the most of all.",
         pattern="le / la / les plus + adjective  ·  le moins + adjective",
         note="The article must match: la plus belle, les plus grands. "
              "'Le plus difficile reste à faire' appears later in this same tale."),
    dict(plane="grammar", term="que je sois",
         text="Mes parents, ils veulent {{c1::que je sois}} méchant.",
         meaning="that I be (subjunctive)",
         intention="After 'vouloir que', the verb changes shape — French forces it.",
         pattern="vouloir que + SUBJUNCTIVE (que je sois, que tu deviennes, que tu fasses)",
         note="Above A1 on paper, but unavoidable: you cannot say 'je veux que tu es'. "
              "The tale uses it twice: 'que je sois méchant' and 'que tu deviennes quelqu'un'."),
    dict(plane="grammar", term="et si vous regrettiez",
         text="{{c1::Et si vous regrettiez}} très fort tous les deux?",
         meaning="what if you were both truly sorry?",
         intention="Make a suggestion or float a hypothesis — a very French move.",
         pattern="Et si + IMPERFECT ?  (et si on partait? et si tu venais?)",
         note="No 'would' needed, no main clause needed. The question mark does the work. "
              "This is how the French say 'how about we...?'"),
    dict(plane="grammar", term="mais si",
         text="Je suis sûr que tu n'as jamais travaillé à l'école. — {{c1::Mais si}}, j'ai travaillé!",
         meaning="yes I did! (contradicting a negative)",
         intention="Say YES to a question or statement that was phrased negatively.",
         pattern="negative statement -> answer SI, never OUI",
         note="French has a third answer word that English and Spanish lack. "
              "'Tu ne viens pas?' — 'Si!' = yes, I am coming."),
    dict(plane="grammar", term="ne sont que",
         text="Il n'y a rien d'écrit, ce {{c1::ne sont que}} des pages toutes blanches.",
         meaning="they are only / nothing but",
         intention="Restrict: 'only'. It looks like a negation but it is not one.",
         pattern="ne + verb + que  (je n'ai que dix euros = I only have ten euros)",
         note="Same two-piece frame as ne...pas, different second piece, opposite job. "
              "Spoken French often drops the 'ne': 'j'ai que dix euros'."),

    # ============ VERBS & CONSTRUCTIONS ============
    dict(plane="verb-construction", term="j'ai froid",
         text="Plus fort, voyons, {{c1::j'ai froid}}!",
         meaning="I'm cold",
         intention="Say how your body feels: cold, hot, hungry, thirsty, scared, sleepy.",
         pattern="avoir + froid / chaud / faim / soif / peur / sommeil / raison",
         note="French uses AVOIR where English uses 'to be'. Never 'je suis froid' "
              "(that would mean you are a cold person)."),
    dict(plane="verb-construction", term="il fait chaud",
         text="{{c1::Il fait chaud}}. — Tu l'as dit, mon enfant.",
         meaning="it's hot (the weather)",
         intention="Talk about the weather — always with faire, always impersonal.",
         pattern="il fait + chaud / froid / beau / mauvais / nuit",
         note="Minimal pair with the card above: 'j'ai chaud' = I feel hot; "
              "'il fait chaud' = the weather is hot. Different verb, different meaning."),
    dict(plane="verb-construction", term="devenir",
         text="Pardon monsieur, je voudrais {{c1::devenir}} gentil. Que dois-je faire?",
         meaning="to become",
         intention="Talk about changing into something: a job, a state, a person.",
         pattern="devenir + noun/adjective (devenir médecin, devenir célèbre)",
         note="Conjugates like venir (je deviens, il devient) and takes ÊTRE in the "
              "past: je suis devenu."),
    dict(plane="verb-construction", term="obéir à",
         text="Eh bien, premièrement, {{c1::obéir à}} ses parents.",
         meaning="to obey",
         intention="Say who you obey — parents, rules, orders.",
         pattern="obéir À quelqu'un (never obéir quelqu'un)",
         note="The preposition is obligatory in French even though English drops it. "
              "Same trap: téléphoner à, répondre à, plaire à."),
    dict(plane="verb-construction", term="essaie d'",
         text="Là-haut, {{c1::essaie d'}}expliquer ton affaire.",
         meaning="try to",
         intention="Say you will attempt something.",
         pattern="essayer DE + infinitive",
         note="The DE is obligatory. 'Je vais essayer' can stand alone with nothing after."),
    dict(plane="verb-construction", term="fais attention",
         text="{{c1::Fais}} bien {{c1::attention}}, l'ange de la lecture est très sévère.",
         meaning="be careful / pay attention",
         intention="Warn someone, or tell them to concentrate.",
         pattern="faire attention À quelque chose / faire attention DE + infinitive",
         note="Polite form: faites attention. One of the most-used faire expressions."),
    dict(plane="verb-construction", term="a l'air",
         text="Il {{c1::a l'air}} malin, ton fils!",
         meaning="looks / seems",
         intention="Describe the impression someone gives, without committing to it.",
         pattern="avoir l'air + adjective (elle a l'air fatiguée, ça a l'air bon)",
         synonyms="sembler, paraître (both more formal)"),
    dict(plane="verb-construction", term="ça marche",
         text="{{c1::Ça marche}}! Ça marche!",
         meaning="it works!",
         intention="Say a machine, a plan or a trick is working.",
         pattern="ça marche / ça ne marche pas",
         note="FALSE FRIEND TRAP: marcher means both 'to walk' AND 'to work "
              "(function)'. 'Ça marche' also means 'deal! / okay!' in conversation."),
]

if __name__ == "__main__":
    deck_builder.build(LANGUAGE, SLUG, DECK_ID, CARDS, LEVEL, DESCRIPTION)
